source "https://rubygems.org"

ruby "3.2.7"

gem "rails", "~> 7.1.2"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "rack-cors", require: "rack/cors"

group :development, :test, :production do
  # gem "sqlite3", "~> 1.4"
end

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
